notifications:
  email:
    recipients:
      - n.zaretskij@gmail.com # Участинки
      - oleksandr.shkuropat@gmail.com
      - winter2007d@gmail.com
    on_success: always # default: change Отправка уведомлений на почту при успешном билде
    on_failure: always # default: always Отправка уведомлений на почту при неуспешном  билде
language: php
php:
  - "7.1"
before_script:
  - composer self-update
  - composer install
script: phpunit --configuration ./wp-content/plugins/quests-city/phpunit.xml --coverage-text

