matrix:
  include:
    - language: node_js
      node_js: 8.9.3
      before_script:
        - npm install mocha chai mathjs sinon gulp gulp-util gulp-mocha
        - npm install mocha gulp -g
      script:
        - gulp mocha
    - language: php
      php: 7.1
      before_script:
      - composer self-update
      - composer install
      script: phpunit --configuration ./phpunit.xml --coverage-text
notifications:
  email:
    recipients:
      - oleksandr.shkuropat@gmail.com # Участинки
      - winter2007d@gmail.com
      - n.zaretskij@gmail.com # Участинки
    on_success: always # default: change Отправка уведомлений на почту при успешном билде
    on_failure: always # default: always Отправка уведомлений на почту при неуспешном  билде